@tokens =Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNjU1NDQxMDYzfQ.Nl6SSD2hw8B01EQX7i8IdmjIAIvq2OpbB8sfGZTl1aU

### VEHICLE POPULAR
GET http://localhost:1616/history/popular HTTP/1.1

### HISTORY BY ID 
GET http://localhost:1616/history/user/2 HTTP/1.1

### PENCARIAN
GET http://localhost:1616/users/ HTTP/1.1


### SEND DATA (CREATE) USER
POST http://localhost:1616/users/ HTTP/1.1
Content-Type: application/json

{
    "username" : "luke",
    "password" : "admin",
    "firstname" : "Luke",
    "lastname" : "Skywalker 2",
    "email" : "skywalker@gmail.com"
}

### SEND DATA (CREATE) VEHICLE
POST http://localhost:1616/vehicles/ HTTP/1.1
Content-Type: application/json

{
    "name" : "Honda beat",
    "city" : "malang",
    "type" : "motorbike",
    "image" : "https://images.unsplash.com/photo-1617045434421-a72d713fc8a0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"
}

### GVEHICLE
GET http://localhost:1616/vehicles/ HTTP/1.1
Authorization: {{tokens}}

### UPDATE DATA
PUT http://localhost:1616/vehicles/update/2
Authorization: {{tokens}}
Content-Type: application/json

{
    "name" : "lamborghini urus",
    "city" : "jakarta",
    "type" : "car",
    "image" : "https://images.unsplash.com/photo-1619097763751-2881df85ed25?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"
}

### DELETE DATA
DELETE http://localhost:1616/users/delete/15 HTTP/1.1
Content-Type: application/json

### READ
GET http://localhost:1616/users/ HTTP/1.1
Authorization: {{tokens}}
Content-Type: application/json

### lOGIN
POST http://localhost:1616/auth/log HTTP/1.1
Content-Type: application/json

{
    "username" : "admin",
    "password" : "admin"
}
